move apt-get install's to one line
remove apt-get upgrade which was crashing on m1 mac on 9/1/24 for some reason
error was:

ERROR: failed to solve: process "/bin/sh -c apt-get upgrade" did not complete successfully: exit code: 1